export const PoolABI = [
  {
    type: 'function',
    name: 'supply',
    inputs: [
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'onBehalfOf', type: 'address', internalType: 'address' },
      { name: 'referralCode', type: 'uint16', internalType: 'uint16' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'to', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'borrow',
    inputs: [
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'interestRateMode', type: 'uint256', internalType: 'uint256' },
      { name: 'referralCode', type: 'uint16', internalType: 'uint16' },
      { name: 'onBehalfOf', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repay',
    inputs: [
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'interestRateMode', type: 'uint256', internalType: 'uint256' },
      { name: 'onBehalfOf', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setUserUseReserveAsCollateral',
    inputs: [
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'useAsCollateral', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getUserAccountData',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'totalCollateralBase', type: 'uint256', internalType: 'uint256' },
      { name: 'totalDebtBase', type: 'uint256', internalType: 'uint256' },
      { name: 'availableBorrowsBase', type: 'uint256', internalType: 'uint256' },
      { name: 'currentLiquidationThreshold', type: 'uint256', internalType: 'uint256' },
      { name: 'ltv', type: 'uint256', internalType: 'uint256' },
      { name: 'healthFactor', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getReservesList',
    inputs: [],
    outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getReserveData',
    inputs: [{ name: 'asset', type: 'address', internalType: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct DataTypes.ReserveDataLegacy',
        components: [
          { name: 'configuration', type: 'tuple', internalType: 'struct DataTypes.ReserveConfigurationMap', components: [{ name: 'data', type: 'uint256' }] },
          { name: 'liquidityIndex', type: 'uint128' },
          { name: 'currentLiquidityRate', type: 'uint128' },
          { name: 'variableBorrowIndex', type: 'uint128' },
          { name: 'currentVariableBorrowRate', type: 'uint128' },
          { name: 'currentStableBorrowRate', type: 'uint128' },
          { name: 'lastUpdateTimestamp', type: 'uint40' },
          { name: 'id', type: 'uint16' },
          { name: 'aTokenAddress', type: 'address' },
          { name: 'stableDebtTokenAddress', type: 'address' },
          { name: 'variableDebtTokenAddress', type: 'address' },
          { name: 'interestRateStrategyAddress', type: 'address' },
          { name: 'accruedToTreasury', type: 'uint128' },
          { name: 'unbacked', type: 'uint128' },
          { name: 'isolationModeTotalDebt', type: 'uint128' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'Supply',
    inputs: [
      { name: 'reserve', type: 'address', indexed: true, internalType: 'address' },
      { name: 'user', type: 'address', indexed: false, internalType: 'address' },
      { name: 'onBehalfOf', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'referralCode', type: 'uint16', indexed: true, internalType: 'uint16' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Withdraw',
    inputs: [
      { name: 'reserve', type: 'address', indexed: true, internalType: 'address' },
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Borrow',
    inputs: [
      { name: 'reserve', type: 'address', indexed: true, internalType: 'address' },
      { name: 'user', type: 'address', indexed: false, internalType: 'address' },
      { name: 'onBehalfOf', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'interestRateMode', type: 'uint8', indexed: false, internalType: 'enum DataTypes.InterestRateMode' },
      { name: 'borrowRate', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'referralCode', type: 'uint16', indexed: true, internalType: 'uint16' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Repay',
    inputs: [
      { name: 'reserve', type: 'address', indexed: true, internalType: 'address' },
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'repayer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'useATokens', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
] as const

